name: Publish to Docker hub
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'releases/**'

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t kermeth/emailer:latest .

      - name: Login and push Docker image
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u kermeth --password-stdin
          docker push kermeth/emailer:latest
